name: "Publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: "Checkout branch: ${{ github.ref }}"
        uses: actions/checkout@v2
        with:
          ## Only a single commit is fetched by default
          ## Set `fetch-depth: 0` to fetch all history
          fetch-depth: 0
          path: main

      - name: "Debug"
        working-directory: main
        run: |
          ls
        
      - name: "Checkout branch: gh-pages"
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Debug"
        working-directory: gh-pages
        run: |
          ls

      - name: "Clean install dependencies and build"
        working-directory: main
        run: |
          ls
          npm install hexo-cli -g
          npm install
          ls
          cp -f custom/default.styl node_modules/hexo-theme-icarus/source/css
          # npm run clean
          npm run build

      - name: "Copy dist files"
        ## Need to specifiy a working-directory, otherwise it cannot find the path
        working-directory: gh-pages
        run: |
          # rm -rf 2020 archives categories css img js tags *.html *.json
          git rm -r *
          mv -f ../main/public/* .

      - name: "Deploy"
        working-directory: gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "deploy"
          git push
