name: "Publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: "Checkout branch: ${{ github.ref }}"
        uses: actions/checkout@v2
        with:
          ## Only a single commit is fetched by default
          ## Set `fetch-depth: 0` to fetch all history
          fetch-depth: 0
          path: main
        
      - name: "Checkout branch: gh-pages"
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Clean install dependencies and build"
        working-directory: main
        run: |
          npm install hexo-cli -g
          npm install
          # cp -f custom/inline.js node_modules/kramed/lib/rules/

          # cp -f custom/default.styl node_modules/hexo-theme-icarus/source/css
          # cp -f custom/base.styl node_modules/hexo-theme-icarus/include/style/
          # cp -f custom/head.jsx node_modules/hexo-theme-icarus/layout/common/
          # cp -f custom/comment.jsx node_modules/hexo-theme-icarus/layout/common/
          # cp -f custom/article.jsx node_modules/hexo-theme-icarus/layout/common/
          # cp -f custom/footer.jsx node_modules/hexo-theme-icarus/layout/common/
          npm run clean
          npm run build

      - name: "Copy dist files"
        ## Need to specify a working-directory, otherwise it cannot find the path
        working-directory: gh-pages
        run: |
          rm -rf *
          ls -a
          cat .gitignore
          # git ls-files 
          # git rm -f *
          # git filter-branch --force *
          # ls -a
          mv -f ../main/public/* .

      # - name: "Setup ssh."
      #   uses: webfactory/ssh-agent@v0.4.1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: "Add known host."
      #   run: ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # - name: "Pull on cloud-server"
      #   run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "git -C ${{ secrets.REPO_PATH}} pull origin main:main"

      # - name: "Call the script on cloud-server to deploy"
      #   run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sh /home/ubuntu/script/deploy.sh"


      - name: "Deploy on gh-pages"
        working-directory: gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "deploy"
          git push