name: "Publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup Node.js environment"
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: "Checkout branch: ${{ github.ref }}"
        uses: actions/checkout@v2
        with:
          ## Only a single commit is fetched by default
          ## Set `fetch-depth: 0` to fetch all history
          fetch-depth: 0
          path: main

      - name: "Checkout branch: gh-pages"
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Clean install dependencies and build"
        working-directory: master
        run: |
          npm install hexo-cli -g
          npm install
          npm run build

      - name: "Deploy"
        working-directory: gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "deploy"
          git push
